create table "public"."articles" (
    "id" bigint generated by default as identity not null,
    "uuid" uuid not null default uuid_generate_v4(),
    "content" text not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "sync_time" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "is_deleted" boolean not null default false
);


alter table "public"."articles" enable row level security;

CREATE UNIQUE INDEX articles_pkey ON public.articles USING btree (id);

CREATE UNIQUE INDEX articles_uuid_key ON public.articles USING btree (uuid);

alter table "public"."articles" add constraint "articles_pkey" PRIMARY KEY using index "articles_pkey";

alter table "public"."articles" add constraint "articles_uuid_key" UNIQUE using index "articles_uuid_key";

create policy "anon 可以完全访问所有文章"
on "public"."articles"
as permissive
for all
to anon
using (true)
with check (true);



